### ISSUE TITLE
Create user documentation incubator via /docs folder

### ISSUE THREAD

**Issue by sthagen** [a-ship-behind-the-moon/letters-from-letters#3]
Simple as abc

**Comment by sthagen** [comment]
@sthagen Please test.

**Comment by sthagen** [comment]
@AntonDrees please test and try to close this issue (maybe with a short OK as comment), so that we also know, you can do things you should be able to.

**Comment by sthagen** [comment]
@AntonDrees please test and try to close this issue (maybe with a short OK as comment), so that we also know, you can do things you should be able to.

**Comment by AntonDrees** [comment]
OK

**Comment by AntonDrees** [comment]
OK
